// Episode data — realistic placeholders inspired by the Agentic Thinking theme.
// YouTube IDs are real public videos so the player embeds work in the prototype.
window.EPISODES = [
  {
    n: 20,
    slug: "designing-multi-agent-memory",
    title: "Designing Multi-Agent Memory",
    blurb: "Why every agent eventually needs a hippocampus, and the tradeoffs between vector stores, episodic logs, and structured scratchpads.",
    tags: ["memory", "architecture", "tool use"],
    duration: "58:12",
    date: "2026-04-14",
    yt: "iBHErQuPO5A",
    host: "host_a",
    guest: "Priya Shah",
    guestRole: "staff eng, orchestration platform",
  },
  {
    n: 19,
    slug: "fabric-data-workflows-for-agents",
    title: "Fabric: Data Workflows for Agents",
    blurb: "Building the warehouse/agent seam. How to keep governance intact when an LLM is the one running the pipeline.",
    tags: ["data", "warehouse", "governance"],
    duration: "47:04",
    date: "2026-04-07",
    yt: "ZXsQAXx_ao0",
    host: "host_b",
    guest: "Marco Ruiz",
    guestRole: "principal, data platforms",
  },
  {
    n: 18,
    slug: "shipping-human-approval-loops",
    title: "Shipping Human Approval Loops",
    blurb: "The quiet hard part: making approvals fast enough that operators don't disable them, and loud enough that they catch the bad cases.",
    tags: ["workflows", "risk", "escalation"],
    duration: "51:36",
    date: "2026-03-31",
    yt: "9bZkp7q19f0",
    host: "host_a",
    guest: "Dana Levin",
    guestRole: "eng lead, risk tooling",
  },
  {
    n: 17,
    slug: "prompting-beyond-static-templates",
    title: "Prompting Beyond Static Templates",
    blurb: "Runtime planning, dynamic few-shot, evaluation in the loop. Prompts as programs, not strings.",
    tags: ["runtime", "evaluation", "tuning"],
    duration: "42:18",
    date: "2026-03-24",
    yt: "kXYiU_JCYtU",
    host: "host_b",
    guest: "Sam Okafor",
    guestRole: "researcher",
  },
  {
    n: 16,
    slug: "the-orchestrator-you-already-have",
    title: "The Orchestrator You Already Have",
    blurb: "Airflow, Temporal, Step Functions — why the 'boring' workflow engines are suddenly the hottest agent infra.",
    tags: ["orchestration", "infra"],
    duration: "49:52",
    date: "2026-03-17",
    yt: "y6120QOlsfU",
    host: "host_a",
    guest: "Lena Park",
    guestRole: "staff, platform infra",
  },
  {
    n: 15,
    slug: "tool-use-is-a-distribution-problem",
    title: "Tool Use Is a Distribution Problem",
    blurb: "Tool selection accuracy collapses past ~40 tools. We dig into retrieval, routing, and the economics of skill libraries.",
    tags: ["tools", "routing", "retrieval"],
    duration: "54:21",
    date: "2026-03-10",
    yt: "L_jWHffIx5E",
    host: "host_b",
    guest: "Ari Koenig",
    guestRole: "applied research",
  },
  {
    n: 14,
    slug: "cost-shaped-agents",
    title: "Cost-Shaped Agents",
    blurb: "Token budgets as a first-class constraint. Rewriting loops so the cheap model does 80% of the work.",
    tags: ["cost", "routing", "cascades"],
    duration: "39:47",
    date: "2026-03-03",
    yt: "fJ9rUzIMcZQ",
    host: "host_a",
    guest: "Wes Tanaka",
    guestRole: "eng, cost platform",
  },
  {
    n: 13,
    slug: "evals-that-survive-contact",
    title: "Evals That Survive Contact",
    blurb: "Why golden sets rot, how to instrument production as your real eval set, and the case for tripwire metrics.",
    tags: ["evaluation", "observability"],
    duration: "46:02",
    date: "2026-02-24",
    yt: "tgbNymZ7vqY",
    host: "host_b",
    guest: "Rin Matsuda",
    guestRole: "quality lead",
  },
  {
    n: 12,
    slug: "sandboxing-for-real-agents",
    title: "Sandboxing for Real Agents",
    blurb: "Giving an agent a shell without giving it the keys. Isolation patterns from the people who actually run them in prod.",
    tags: ["security", "sandbox", "infra"],
    duration: "52:30",
    date: "2026-02-17",
    yt: "3JZ_D3ELwOQ",
    host: "host_a",
    guest: "Hugo Brandt",
    guestRole: "security eng",
  },
  {
    n: 11,
    slug: "retrieval-is-a-ui-problem",
    title: "Retrieval Is a UI Problem",
    blurb: "The best RAG wins aren't new embeddings — they're better ways to show provenance and let users steer.",
    tags: ["retrieval", "rag", "ux"],
    duration: "44:14",
    date: "2026-02-10",
    yt: "RgKAFK5djSk",
    host: "host_b",
    guest: "Elena Vasquez",
    guestRole: "design eng",
  },
  {
    n: 10,
    slug: "operators-log-ten-episodes-in",
    title: "Operator's Log: Ten Episodes In",
    blurb: "Rebroadcast roundtable. What we got wrong about agent reliability, long-context, and the 'full autonomy' narrative.",
    tags: ["meta", "retrospective"],
    duration: "1:02:45",
    date: "2026-02-03",
    yt: "OPf0YbXqDm0",
    host: "both",
    guest: "— roundtable —",
    guestRole: "",
  },
  {
    n: 9,
    slug: "long-context-is-a-lie-we-tell-ourselves",
    title: "Long Context Is a Lie We Tell Ourselves",
    blurb: "200k-token windows look great on a spec sheet and terrible in practice. What actually works.",
    tags: ["context", "attention", "architecture"],
    duration: "41:10",
    date: "2026-01-27",
    yt: "CevxZvSJLk8",
    host: "host_a",
    guest: "Nate Quill",
    guestRole: "research eng",
  },
  {
    n: 8,
    slug: "structured-output-all-the-way-down",
    title: "Structured Output All the Way Down",
    blurb: "When to force JSON, when to parse prose, and why the right answer is almost always 'fewer free-text fields'.",
    tags: ["schemas", "api design"],
    duration: "38:22",
    date: "2026-01-20",
    yt: "60ItHLz5WEA",
    host: "host_b",
    guest: "Junior Oyelaran",
    guestRole: "api lead",
  },
  {
    n: 7,
    slug: "the-case-against-chat",
    title: "The Case Against Chat",
    blurb: "Chat is a lowest-common-denominator UI. A tour of the surfaces replacing it: canvases, inboxes, dashboards, CLIs.",
    tags: ["ux", "product"],
    duration: "45:57",
    date: "2026-01-13",
    yt: "2vjPBrBU-TM",
    host: "host_a",
    guest: "Farah Nasir",
    guestRole: "design lead",
  },
  {
    n: 6,
    slug: "fine-tuning-in-2026",
    title: "Fine-Tuning in 2026",
    blurb: "RLHF is out, DPO is boring, distillation is undervalued. A working engineer's view of the current stack.",
    tags: ["training", "distillation"],
    duration: "50:08",
    date: "2026-01-06",
    yt: "hTWKbfoikeg",
    host: "host_b",
    guest: "Ivy Chen",
    guestRole: "research eng",
  },
  {
    n: 5,
    slug: "observability-for-nondeterminism",
    title: "Observability for Nondeterminism",
    blurb: "Traces are not enough. How to build the dashboards you actually need when every run is different.",
    tags: ["observability", "traces"],
    duration: "43:33",
    date: "2025-12-30",
    yt: "SlPhMPnQ58k",
    host: "host_a",
    guest: "Theo Albrecht",
    guestRole: "observability eng",
  },
  {
    n: 4,
    slug: "what-the-workflow-gets-right",
    title: "What 'The Workflow' Gets Right",
    blurb: "Chains, DAGs, state machines. The shape of the graph matters more than the model you stuck in each node.",
    tags: ["orchestration", "architecture"],
    duration: "47:41",
    date: "2025-12-23",
    yt: "JGwWNGJdvx8",
    host: "host_b",
    guest: "Omar Jafari",
    guestRole: "staff eng",
  },
  {
    n: 3,
    slug: "agents-in-anger",
    title: "Agents in Anger",
    blurb: "Three operators talk through the incidents they can share: runaway loops, silent skips, auth drift.",
    tags: ["incidents", "postmortem"],
    duration: "56:12",
    date: "2025-12-16",
    yt: "lp-EO5I60KA",
    host: "both",
    guest: "— panel —",
    guestRole: "",
  },
  {
    n: 2,
    slug: "the-case-for-small-models",
    title: "The Case for Small Models",
    blurb: "Latency, cost, privacy, and the pleasure of running something you can actually reason about.",
    tags: ["small models", "infra"],
    duration: "40:28",
    date: "2025-12-09",
    yt: "kffacxfA7G4",
    host: "host_a",
    guest: "Pavel Morozov",
    guestRole: "inference eng",
  },
  {
    n: 1,
    slug: "hello-world",
    title: "hello_world",
    blurb: "Why we're doing this. What the show is, who it's for, and a promise to stay unglamorous.",
    tags: ["meta", "kickoff"],
    duration: "32:15",
    date: "2025-12-02",
    yt: "kJQP7kiw5Fk",
    host: "both",
    guest: "— hosts —",
    guestRole: "",
  },
];

window.HOSTS = {
  host_a: {
    handle: "host_a",
    name: "Ren Carver",
    role: "Staff engineer · orchestration platforms",
    bio: "Ren has shipped agents in anger at three companies and has the scars to prove it. Spends weekends rewriting their own prompt library. Prefers a REPL to a whiteboard.",
    links: [
      { label: "github.com/rencarver", href: "#" },
      { label: "ren@agentic-thinking.dev", href: "#" },
    ],
  },
  host_b: {
    handle: "host_b",
    name: "Joss Okonkwo",
    role: "Principal · data + ML platforms",
    bio: "Joss thinks about the seam between warehouses and agents. Previously led evals at a mid-sized foundation model lab. Will die on the hill that boring orchestration beats clever prompts.",
    links: [
      { label: "github.com/jossok", href: "#" },
      { label: "joss@agentic-thinking.dev", href: "#" },
    ],
  },
};

// Chapters + transcript for the "current" episode (top one). Others share same mock
// so the prototype feels populated.
window.CHAPTERS = [
  { t: 0, label: "cold open" },
  { t: 92, label: "what 'memory' actually means for an agent" },
  { t: 410, label: "vector stores are a cache, not a brain" },
  { t: 812, label: "episodic vs. semantic logs" },
  { t: 1204, label: "structured scratchpads and the case for SQL" },
  { t: 1720, label: "failure modes: stale memory, context poisoning" },
  { t: 2210, label: "eval harnesses for memory systems" },
  { t: 2680, label: "closing: the hippocampus you actually need" },
  { t: 3020, label: "listener question: memory across users" },
  { t: 3280, label: "outro" },
];

window.TRANSCRIPT = [
  { t: 0, s: "host_a", text: "Welcome back. This is Agentic Thinking, episode twenty. I'm Ren." },
  { t: 6, s: "host_b", text: "And I'm Joss. Today we are talking about memory. Not the metaphor, the actual plumbing." },
  { t: 14, s: "guest", text: "Happy to be here. I run the orchestration platform at a shop where this question comes up every single planning cycle." },
  { t: 24, s: "host_a", text: "Let's start with the bait. People say 'agent memory' and usually mean four different things. Can we disambiguate?" },
  { t: 36, s: "guest", text: "Sure. There's session context — what's in the current window. There's retrieved knowledge — stuff you pull in at runtime. There's episodic memory — the log of what has happened before. And there's learned behavior — whatever you've baked into weights or a fine-tune." },
  { t: 72, s: "host_b", text: "And most conversations collapse those into 'the vector DB'." },
  { t: 78, s: "guest", text: "Right. Which works until it doesn't. A vector store is a cache. It's great for 'have I seen this before'. It is terrible for 'what did the user commit to last Tuesday'." },
  { t: 92, s: "host_a", text: "Okay, chapter one. What does 'memory' actually mean for an agent, if we're being precise." },
  { t: 108, s: "guest", text: "The definition I've converged on: memory is whatever persists between invocations and changes the next invocation's behavior. By that definition, a prompt template is memory. A config flag is memory. It forces you to be honest about your surface area." },
  { t: 140, s: "host_b", text: "That matches what we saw at the last place I worked. The 'memory bug' turned out to be a stale feature flag, not the embeddings." },
  { t: 158, s: "host_a", text: "Let's get concrete. Someone is starting a new project. They need 'memory'. Where should they start?" },
  { t: 172, s: "guest", text: "Log everything. Structured. Boring. Before you touch a vector store, you want a table or a file that records: what the user said, what the agent did, what tools it called, what the outcome was. Ninety percent of 'memory' questions are answered by a good log." },
  { t: 210, s: "host_b", text: "Append-only, ideally." },
  { t: 214, s: "guest", text: "Append-only. With a schema. If you can't grep for a run by user and date, you don't have memory, you have vibes." },
  { t: 240, s: "host_a", text: "Let's talk about the vector store trap, which is kind of the setup for the next chapter." },
  { t: 252, s: "guest", text: "The trap is: you reach for similarity search because it's the first tool that's easy to spin up. But most of what you want from memory is not similarity. It's recency, authorship, or exact match. And you end up with a pile of embeddings that answer the wrong question quickly." },
  { t: 288, s: "host_b", text: "The part I want to push on: when IS the vector store the right call?" },
  { t: 298, s: "guest", text: "When the thing you're retrieving is genuinely unstructured prose and you have more of it than a human can scan. Documentation. Past meeting notes. Long incident writeups. If it fits in a table, put it in a table first." },
  { t: 330, s: "host_a", text: "Good heuristic. We should come back to hybrid retrieval in a minute." },
  { t: 340, s: "host_b", text: "Before that — one thing listeners keep writing in about: cross-session memory. How do you keep state across days without the agent drifting." },
  { t: 360, s: "guest", text: "Two answers. One: keep a summary object per user that you explicitly curate. Small, structured, updated with review. Two: treat long-term memory as a write queue, not a write-through cache. Humans or heuristics promote things into the persistent store." },
  { t: 398, s: "host_a", text: "Reviewers in the loop." },
  { t: 402, s: "guest", text: "Always, at first. You can automate later, once you see what's actually worth persisting." },
  { t: 410, s: "host_b", text: "Chapter two. Vector stores are a cache, not a brain." },
  { t: 422, s: "guest", text: "I wrote a post with that title and got yelled at by four different vendors. Stand by it. A brain has goals, self-regulation, and forgetting. A cache has keys and values." },
  { t: 452, s: "host_a", text: "The forgetting part is underrated." },
  { t: 458, s: "guest", text: "Massively. The best memory systems I've seen forget aggressively. They demote, expire, and overwrite. If your embedding count only goes up, you're going to have a bad time in month six." },
  { t: 490, s: "host_b", text: "We should talk about TTLs and compaction." },
  { t: 500, s: "guest", text: "A soft TTL by default — say thirty days. Anything older gets summarized into a higher-level entry and the raw vectors are dropped. It costs more up front, saves you in every later incident." },
  { t: 540, s: "host_a", text: "Let's pivot. Listener question we got last week: how do you handle memory across different users, especially with privacy constraints." },
  { t: 560, s: "guest", text: "Treat user memory as a first-class tenant. Don't colocate. Don't share embeddings across users even if the content looks identical. The amount of cross-contamination you can hide in a shared index is scary." },
  { t: 598, s: "host_b", text: "Plus the obvious legal reasons." },
  { t: 602, s: "guest", text: "Plus those. But even ignoring legal: it's bad engineering." },
  { t: 620, s: "host_a", text: "Closing thought before we flip to episodic memory." },
  { t: 630, s: "guest", text: "If you only take one thing from this chapter: pretend the vector store costs a hundred times what it costs. You'll build better." },
  { t: 812, s: "host_b", text: "Alright, episodic vs. semantic. Give us the picture." },
  { t: 822, s: "guest", text: "Episodic is 'this specific thing happened on this date.' Semantic is 'this is how we do X around here.' Agents need both and they need them in different stores." },
  { t: 1204, s: "host_a", text: "Structured scratchpads. This is your bit." },
  { t: 1212, s: "guest", text: "My bit. Structured scratchpads are a boring idea that keeps paying off. Give the agent a small, typed blob it can read and write during a run. Don't let it scribble free text and hope." },
  { t: 1720, s: "host_b", text: "Failure modes. What breaks memory systems in production." },
  { t: 1732, s: "guest", text: "Staleness. Poisoning. Schema drift. In that order." },
  { t: 2210, s: "host_a", text: "Eval harnesses — how do you even test a memory system?" },
  { t: 2222, s: "guest", text: "Replay. You need to be able to replay a week of traffic against a new memory config and get a diff. If you don't have that, you're flying blind." },
  { t: 2680, s: "host_b", text: "Okay. Closing. The hippocampus you actually need." },
  { t: 2692, s: "guest", text: "It's smaller than you think. It's more structured than you think. And it's mostly a really good append-only log with a few curated views on top. Start there." },
  { t: 3020, s: "host_a", text: "Listener question to close. Mei in Berlin asks: how should memory behave across multiple users who share a team?" },
  { t: 3040, s: "guest", text: "Scope memory to the team, not the user, for shared projects. Keep a per-user private layer. Let people promote things from private to team with an explicit action. Never promote automatically." },
  { t: 3280, s: "host_b", text: "That's our show. Links and chapters in the notes. Thanks Priya." },
  { t: 3288, s: "guest", text: "Thanks for having me." },
  { t: 3292, s: "host_a", text: "Next week: data workflows for agents, with Marco. Until then, keep the terminal open." },
];
